LU2019-118: remove unused const variables
GCC 8.3 complains:

   CC       src/publisher_subscriber/test/cmsg_publisher_subscriber_unit_tests-data_unit_tests.o
 ../../cmsg/cmsg/test/functional/publisher_subscriber_tests.c:30:23: error: 'tipc_scope' defined but not used [-Werror=unused-const-variable=]
  static const uint16_t tipc_scope = TIPC_NODE_SCOPE;
                        ^~~~~~~~~~
 ../../cmsg/cmsg/test/functional/publisher_subscriber_tests.c:29:23: error: 'tipc_instance' defined but not used [-Werror=unused-const-variable=]
  static const uint16_t tipc_instance = 1;
                        ^~~~~~~~~~~~~

Remove the unused variables.

Change-Id: Ia49992d7d7ef0dd7d47798cea8b37934df3090f7
Reviewed-by: Matt Bennett <matt.bennett@alliedtelesis.co.nz>
Signed-off-by: Kyeong Yoo <kyeong.yoo@alliedtelesis.co.nz>